import "@radix-ui/themes/styles.css";
import { Inter } from "next/font/google";
import "./globals.css";
import "./theme-config.css";

import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import { Metadata } from "next";
import { SkeletonTheme } from "react-loading-skeleton";
import NavBar from "./NavBar";
import QueryClientProvider from "./QueryClientProvider";
import AuthProvider from "./auth/Provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} dark`}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme
              appearance="dark"
              accentColor="teal"
              grayColor="gray"
              radius="large"
              scaling="110%"
            >
              <SkeletonTheme baseColor="#2c2c2c" highlightColor="#cccccc">
                <NavBar />
                <main className="p-5">
                  <Container>{children}</Container>
                </main>
              </SkeletonTheme>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
