import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import { Inter } from "next/font/google";

import "@radix-ui/themes/styles.css";
import NavBar from "./NavBar";
import { Container, Theme } from "@radix-ui/themes";
import { Metadata } from "next";
import { SkeletonTheme } from "react-loading-skeleton";
import AuthProvider from "./auth/Provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <AuthProvider>
          <Theme appearance="light" accentColor="violet" radius="large">
            <SkeletonTheme baseColor="grey" highlightColor="#444">
              <NavBar />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
            </SkeletonTheme>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
